package repo

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/perfect-panel/server/internal/module/subscription/entity/usersub"
	"github.com/perfect-panel/server/pkg/cache"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

// postgresUserSubscribe is the production user_subscribe table of the
// PostgreSQL migrations (00001 with the columns 02119, 03000 and 03020 add):
// zone-less TIMESTAMP(3) columns, which keep the wall clock of the value
// written and return it in the session's zone.
const postgresUserSubscribe = `CREATE TABLE user_subscribe (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, order_id BIGINT NOT NULL, subscribe_id BIGINT NOT NULL,
 start_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), expire_time TIMESTAMP(3) DEFAULT NULL,
 finished_at TIMESTAMP(3) DEFAULT NULL, traffic_reset_at TIMESTAMP(3) DEFAULT NULL,
 traffic BIGINT DEFAULT 0, download BIGINT DEFAULT 0, upload BIGINT DEFAULT 0,
 token VARCHAR(255) DEFAULT '' UNIQUE, uuid VARCHAR(255) DEFAULT '' UNIQUE, status SMALLINT DEFAULT 0,
 note VARCHAR(500) DEFAULT '', entitlement_source VARCHAR(32) NOT NULL DEFAULT '',
 created_at TIMESTAMP(3) DEFAULT NULL, updated_at TIMESTAMP(3) DEFAULT NULL)`

// openPostgresSubscribes opens the PostgreSQL test database
// (PPANEL_TEST_POSTGRES_DSN, a postgres:// URL) on a schema of its own, with
// the session zone set to zone the way the application's DSN sets it to
// AppLocation, and creates the production user_subscribe table there. The
// test skips without the DSN.
func openPostgresSubscribes(t *testing.T, zone string) *gorm.DB {
	t.Helper()
	dsn := os.Getenv("PPANEL_TEST_POSTGRES_DSN")
	if dsn == "" {
		t.Skip("set PPANEL_TEST_POSTGRES_DSN to run the PostgreSQL expiry test")
	}
	u, err := url.Parse(dsn)
	if err != nil || u.Scheme == "" {
		t.Fatalf("PPANEL_TEST_POSTGRES_DSN must be a postgres:// URL: %v", err)
	}
	silent := &gorm.Config{Logger: gormlogger.Default.LogMode(gormlogger.Silent)}
	admin, err := gorm.Open(postgres.Open(dsn), silent)
	if err != nil {
		t.Fatal(err)
	}
	schema := fmt.Sprintf("expiry_%d", time.Now().UnixNano())
	if err := admin.Exec("CREATE SCHEMA " + schema).Error; err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = admin.Exec("DROP SCHEMA " + schema + " CASCADE").Error
		if conn, err := admin.DB(); err == nil {
			_ = conn.Close()
		}
	})
	query := u.Query()
	query.Set("search_path", schema)
	query.Set("TimeZone", zone)
	// The dialector reads TimeZone from the raw DSN, so the zone's slash must
	// stay visible (as orm.encodePostgresParams keeps it for the application).
	u.RawQuery = strings.ReplaceAll(query.Encode(), "%2F", "/")
	db, err := gorm.Open(postgres.Open(u.String()), silent)
	if err != nil {
		t.Fatal(err)
	}
	if conn, err := db.DB(); err == nil {
		t.Cleanup(func() { _ = conn.Close() })
	}
	if err := db.Exec(postgresUserSubscribe).Error; err != nil {
		t.Fatal(err)
	}
	return db
}

// expectIDs fails unless subs are exactly the rows want lists, in order.
func expectIDs(t *testing.T, what string, subs []*usersub.Subscribe, want string) {
	t.Helper()
	ids := make([]int64, 0, len(subs))
	for _, sub := range subs {
		ids = append(ids, sub.Id)
	}
	if got := fmt.Sprint(ids); got != want {
		t.Fatalf("%s selects %s, want %s", what, got, want)
	}
}

func loadSubscribe(t *testing.T, db *gorm.DB, id int64) *usersub.Subscribe {
	t.Helper()
	var sub usersub.Subscribe
	if err := db.First(&sub, id).Error; err != nil {
		t.Fatal(err)
	}
	return &sub
}

// insertExpiryRows stores two no-limit subscriptions whose markers were
// written in UTC and in Asia/Shanghai, one elapsed term and one running
// term, for plan 7, and checks that the column kept two different wall
// clocks for the markers.
func insertExpiryRows(t *testing.T, db *gorm.DB, now time.Time) {
	t.Helper()
	shanghai, err := time.LoadLocation("Asia/Shanghai")
	if err != nil {
		t.Fatal(err)
	}
	started := now.Add(-48 * time.Hour)
	rows := []usersub.Subscribe{
		{Id: 1, UserId: 1, SubscribeId: 7, StartTime: started, Status: usersub.SubscribeStatusActive, ExpireTime: time.UnixMilli(0).In(time.UTC)},
		{Id: 2, UserId: 2, SubscribeId: 7, StartTime: started, Status: usersub.SubscribeStatusActive, ExpireTime: time.UnixMilli(0).In(shanghai)},
		{Id: 3, UserId: 3, SubscribeId: 7, StartTime: started, Status: usersub.SubscribeStatusActive, ExpireTime: now.Add(-time.Minute)},
		{Id: 4, UserId: 4, SubscribeId: 7, StartTime: started, Status: usersub.SubscribeStatusActive, ExpireTime: now.Add(time.Hour)},
	}
	for i := range rows {
		rows[i].Token, rows[i].UUID = fmt.Sprintf("token-%d", rows[i].Id), fmt.Sprintf("uuid-%d", rows[i].Id)
	}
	if err := db.Create(&rows).Error; err != nil {
		t.Fatal(err)
	}
	var stored []string
	if err := db.Raw("SELECT to_char(expire_time, 'YYYY-MM-DD HH24:MI:SS') FROM user_subscribe WHERE id IN (1, 2) ORDER BY id").Scan(&stored).Error; err != nil {
		t.Fatal(err)
	}
	if fmt.Sprint(stored) != "[1970-01-01 00:00:00 1970-01-01 08:00:00]" {
		t.Fatalf("stored markers = %v, want the epoch's wall clock in UTC and in Asia/Shanghai", stored)
	}
}

// checkServable asserts that the node user list serves both no-limit rows
// and the running one, in SQL and in Go on the rows read back.
func checkServable(t *testing.T, db *gorm.DB, now time.Time) {
	t.Helper()
	var served []*usersub.Subscribe
	if err := servableSubscribes(db, []int64{7}, now).Find(&served).Error; err != nil {
		t.Fatal(err)
	}
	expectIDs(t, "the node user list", served, "[1 2 4]")
	for _, id := range []int64{1, 2} {
		sub := loadSubscribe(t, db, id)
		if !usersub.NoExpiry(sub.ExpireTime) || !sub.ServableAt(now) {
			t.Fatalf("row %d reads back as %v: NoExpiry %v, servable %v", id, sub.ExpireTime, usersub.NoExpiry(sub.ExpireTime), sub.ServableAt(now))
		}
	}
}

// checkSweep runs the lifecycle sweep's selection and finishing statement:
// only the elapsed term is expired.
func checkSweep(t *testing.T, subs *UserSubscriptionRepo, db *gorm.DB, now time.Time) {
	t.Helper()
	ctx := context.Background()
	expired, err := subs.FindExpiredSubscribes(ctx, now)
	if err != nil {
		t.Fatal(err)
	}
	expectIDs(t, "the sweep", expired, "[3]")
	if err := subs.MarkSubscribesFinished(ctx, []int64{1, 2, 3}, usersub.SubscribeStatusExpired, now); err != nil {
		t.Fatal(err)
	}
	for id, want := range map[int64]uint8{1: usersub.SubscribeStatusActive, 2: usersub.SubscribeStatusActive, 3: usersub.SubscribeStatusExpired, 4: usersub.SubscribeStatusActive} {
		if got := loadSubscribe(t, db, id).Status; got != want {
			t.Fatalf("after the sweep row %d has status %d, want %d", id, got, want)
		}
	}
}

// checkReminderAndReset asserts that the expiry reminder never announces a
// no-limit subscription while the calendar traffic reset keeps it in its
// term.
func checkReminderAndReset(t *testing.T, subs *UserSubscriptionRepo, now time.Time) {
	t.Helper()
	ctx := context.Background()
	expiring, err := subs.FindExpiringSubscribes(ctx, now, now.Add(72*time.Hour))
	if err != nil {
		t.Fatal(err)
	}
	expectIDs(t, "the reminder", expiring, "[4]")
	candidates, err := subs.FindTrafficResetCandidates(ctx, []int64{7}, now, now.Truncate(24*time.Hour))
	if err != nil {
		t.Fatal(err)
	}
	expectIDs(t, "the traffic reset", candidates, "[1 2 4]")
}

// TestPostgresNoLimitExpiryIsZoneIndependent stores the no-limit marker in
// the two wall clocks a process whose host zone differs from AppLocation
// writes (the epoch of each zone) and reads them back in a session zone, as
// the application does on PostgreSQL. Both rows are servable in SQL and in
// Go, the lifecycle sweep and the expiry reminder leave them alone, the
// calendar traffic reset still sees them, and a real expiry still expires.
func TestPostgresNoLimitExpiryIsZoneIndependent(t *testing.T) {
	for _, zone := range []string{"UTC", "Asia/Shanghai"} {
		t.Run(zone, func(t *testing.T) {
			db := openPostgresSubscribes(t, zone)
			session, err := time.LoadLocation(zone)
			if err != nil {
				t.Fatal(err)
			}
			// Real times are written in the session zone, as the application
			// writes them in AppLocation; only the markers carry other zones.
			now := time.Now().In(session).Truncate(time.Millisecond)
			insertExpiryRows(t, db, now)
			checkServable(t, db, now)
			subs := NewUserSubscriptionRepo(cache.NewConn(db, nil))
			checkSweep(t, subs, db, now)
			checkReminderAndReset(t, subs, now)
		})
	}
}
